# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Dropcart
tagline:             Website documentatie
url:                 https://dropcart.nl
paginate:            1
baseurl:             "http://dropcart.github.io/documentation/"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed